name: Generate Datas

on:
  schedule:
    - cron: "0 */12 * * *"  # Executa a cada 12 horas
  workflow_dispatch:  # Permite execução manual

permissions:
  contents: write  # Garante permissão para modificar arquivos

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Gerar Snake Animation
        uses: Platane/snk@v3  # Atualizado para a versão mais recente
        id: snake-gif
        with:
          github_user_name: "brunop-lima"  # Verifique se está correto
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: Verificar se os arquivos foram gerados
        run: |
          ls dist
          test -f dist/github-contribution-grid-snake.svg
          test -f dist/github-contribution-grid-snake-dark.svg
          test -f dist/github-contribution-grid-snake.gif

      - name: Publicar no GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0  # Versão atualizada
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
